upgrade to django 2.0 and add mock urls/views for all the issues
oxfordpython/oxfordpython.com pull request #3
Opened 2018-03-12 22:10 UTC by lpmi-13

this may be an incredibly uncouth method of upgrading to django 2.0, but figured I'd give it a bash and see what people think. Happy to change any of this and/or just make incremental changes on smaller feature branches to the original repo, but figured as we're starting more or less from square 1, might as well just start a new project 2.0-style.

Fully intending to refactor as we go.

2018-03-12 22:47 UTC, LilyFirefly requested changes

2018-03-12 22:47 UTC, Ian-Foote commented on oxfordpython/settings.py
> +SECRET_KEY = 'y54h%=s#!+=#-oahz$spl9lhu(*c0y7@+^*c0)q+9g=7)5-9=8'
We should configure this with an environment variable. https://www.mattlayman.com/2017/12-factor-django-apps.html

2018-03-12 22:47 UTC, Ian-Foote commented on oxfordpython/settings.py
> +DEBUG = True
This can also be an environment variable.

2018-03-12 23:30 UTC, craigloftus commented
I'd stick to atomic PRs. It is much easier to review, merge and make progress.

From a quick scan for Django 2 support we only need the change to `MIDDLEWARE` and removing the reference to `SessionAuthenticationMiddleware`

2018-03-13 11:35 UTC, lpmi-13 commented
Thanks for the comments, Craig and Ian...just the kind of feedback I was looking for!

I'll get on this and hopefully have a revised PR posthaste.

2018-03-13 19:42 UTC, lpmi-13 commented
alright, made another feature branch for just the django version upgrade, and will close this and open a PR from there.

2018-03-13 19:42 UTC, closed without merging