update urls to be in line with django 2.0 conventions
oxfordpython/oxfordpython.com pull request #5
Opened 2018-03-18 20:14 UTC by lpmi-13

update to use path instead of url, which seems to be recommended with Django 2.x, though happy to discuss if that's not the way to go.

2018-03-18 20:15 UTC, LilyFirefly approved these changes

2018-03-19 08:30 UTC, craigloftus requested changes
The PR isn't based on the HEAD of the single_page branch, it hasn't caused a merge conflict in this instance but it did make testing it a bit confusing.

2018-03-19 08:30 UTC, craigloftus commented on oxfordpython/urls.py
> +    path('admin', admin.site.urls),
This should be `admin/`; You end up with urls like `adminlogin` otherwise.

2018-03-19 08:38 UTC, lpmi-13 commented
Ah of course. Forgot to pull on single_pages after my own PR was merged.
Will sort!

On Mon, 19 Mar 2018, 08:30 Craig Loftus, <notifications@github.com> wrote:

> *@craigloftus* requested changes on this pull request.
>
> The PR isn't based on the HEAD of the single_page branch, it hasn't caused
> a merge conflict in this instance but it did make testing it a bit
> confusing.
> ------------------------------
>
> In oxfordpython/urls.py
> <https://github.com/oxfordpython/oxfordpython.com/pull/5#discussion_r175357272>
> :
>
> >  from django.contrib import admin
>
>  from .main import views as main_views
>
>  urlpatterns = [
> -    url(r'^admin/', admin.site.urls),
> -    url(r'^$', main_views.HomeView.as_view(), name='home'),
> +    path('admin', admin.site.urls),
>
> This should be admin/; You end up with urls like adminlogin otherwise.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/oxfordpython/oxfordpython.com/pull/5#pullrequestreview-104870287>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AE1etGKGdkdMubrclpWEQoRdr9t--uJ4ks5tf2y1gaJpZM4SvWzA>
> .
>

2018-03-19 22:06 UTC, lpmi-13 commented
decided to close this, as I wanted to add some test cases and starting from a new branch seemed sensible for that fresh clean feeling.

2018-03-19 22:06 UTC, closed without merging